version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk


    working_directory: /dockerapp

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test
      - run:
          name: Build project
          command: ./gradlew build -x test
      - run:
          name: Build Docker Image
          command: |
            docker-compose build
      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag solidtdd_spring-docker $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker tag solidtdd_spring-docker $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dockerapp:latest